Created discussion_entry_created event model
atomicjolt/atomic_insight pull request #34
Opened 2021-05-18 19:18 UTC by sethduffin

2021-05-18 19:27 UTC, kylehovey requested changes

2021-05-18 19:27 UTC, kylehovey commented on migrations/20210518184240_create_discussion_entry_created_event.go
> +type EventMetadata struct {
We should consider adding `pg:",notnull"` to any fields that we expect to be there.

2021-05-18 19:27 UTC, kylehovey commented on migrations/20210518184240_create_discussion_entry_created_event.go
> +	EventTime          time.Time
If `DiscussionEntryCreatedEvent` has one `EventMetadata`, then you'll need to add a
```
DiscussionEntryCreatedEventID int64 `pg:"on_delete:CASCADE"`
```

field on this struct.

2021-05-18 19:27 UTC, kylehovey commented on migrations/20210518184240_create_discussion_entry_created_event.go
> +	EventTime          time.Time
Also, should we add the `Timestamps` to this model?

2021-05-18 19:27 UTC, kylehovey commented on migrations/20210518184240_create_discussion_entry_created_event.go
> +		CreatedAt               time.Time `pg:",notnull"`
The `Timestamps` struct in the `model` package lets you embed the `CreatedAt` etc... fields in a general and reusable way

2021-05-18 19:27 UTC, kylehovey commented on migrations/20210518184240_create_discussion_entry_created_event.go
> +	Body     struct {
Is this a has one relationship, or does this nested `struct` represent something else in `go-pg`?

2021-05-18 20:14 UTC, sethduffin commented on migrations/20210518184240_create_discussion_entry_created_event.go
> +type EventMetadata struct {
EventMetadata is slightly different depending on the event but they all have the fields:
* `EventName`
* `EventTime`
I'll add `pg:",notnull"` to those

2021-05-18 20:14 UTC, sethduffin commented on migrations/20210518184240_create_discussion_entry_created_event.go
> +	EventTime          time.Time
`EventMetadata` isn't necessarily its own model, it's just a reusable struct for the json from the canvas live event.
But maybe I should just define it is as a json string and remove the struct?

2021-05-18 20:14 UTC, sethduffin commented on migrations/20210518184240_create_discussion_entry_created_event.go
> +		CreatedAt               time.Time `pg:",notnull"`
This field comes from the canvas live event json.
Should the body field also just be a json string?

2021-05-18 20:35 UTC, kylehovey commented on migrations/20210518184240_create_discussion_entry_created_event.go
> +		CreatedAt               time.Time `pg:",notnull"`
Never mind, I didn't know that this `CreatedAt` field came from Canvas. Maybe we should rename this to `CanvasCreatedAt` or something like that?

2021-05-18 23:55 UTC, kylehovey commented on migrations/20210518184240_create_discussion_entry_created_schema.go
> +	EventID int64 `pg:"on_delete:CASCADE"`
In order for the ORM to locate the association, this would have to be `DiscussionEntryCreatedEventID` (same for the `Body`)

2021-05-19 00:43 UTC, sethduffin commented on migrations/20210518184240_create_discussion_entry_created_schema.go
> +	EventID int64 `pg:"on_delete:CASCADE"`
Good to know, thanks!

2021-05-19 01:01 UTC, kylehovey approved these changes

2021-05-19 01:03 UTC, merged