Events handler
atomicjolt/atomic_insight pull request #37
Opened 2021-05-20 21:35 UTC by sethduffin

2021-05-20 22:20 UTC, kylehovey requested changes

2021-05-20 22:20 UTC, kylehovey commented on controllers/events_handler.go
> +		eventName := vars["name"]
When getting values from a map in Go, I think we should check for presence and return an error if the field is not there. You would do that like this:

```go
eventName, ok := vars["name"]
if !ok {
  panic("Event name not provided.")
}
 ```

2021-05-20 22:20 UTC, kylehovey commented on controllers/events_handler.go
> +		case "GET":
I don't think we need to implement `GET` since the GraphQL API handles querying the database

2021-05-20 22:20 UTC, kylehovey commented on controllers/events_handler.go
> +			eventName := string(regexp.MustCompile(`"event_name": ?"([^"]*)"`).FindSubmatch(body)[1])
Could we just unmarshall the JSON to get this info? We could include that in a library in a function that is like `canvasEvents.EventNameOf(payload)`, or something else like that.

2021-05-20 22:20 UTC, kylehovey commented on repo/discussion_entry_created_event_repo.go
> +	if err != nil {
I wonder if we should also check the shape of the data against what we expect, but that may be a lot of additional work. Eventually this endpoint will be only communicating by using signed JWT's, so we may be able to use that as our guarantee instead of a schema validation.

2021-05-20 22:20 UTC, kylehovey commented on controllers/events_handler.go
> +		eventName := vars["name"]
Also, since we will most likely just be using HTTP POST for this, the POST body would be the place to put this information, rather than the path.

2021-05-20 22:20 UTC, kylehovey commented on controllers/events_handler.go
> +		invalidRequestErr := fmt.Errorf("Invalid request method: %q", r.Method)
We may not want to instantiate these errors each time if each one is only getting used in one line elsewhere.

2021-05-20 22:23 UTC, kylehovey commented on controllers/events_handler.go
> +			eventName := string(regexp.MustCompile(`"event_name": ?"([^"]*)"`).FindSubmatch(body)[1])
Alternatively, we could throw that function in the `lib` package (it may become a kitchen sink, but for now it's nice to have a place to put functionality that may be common to multiple areas).

2021-05-20 22:24 UTC, kylehovey commented on controllers/events_handler.go
> +func writeAndPanic(w http.ResponseWriter, err error) {
Here's the handler we use: https://pkg.go.dev/github.com/gorilla/handlers?utm_source=godoc#RecoveryHandler

2021-05-20 22:26 UTC, CarsonFox commented on controllers/events_handler.go
> +func writeAndPanic(w http.ResponseWriter, err error) {
Yeah, gorilla mux has a middleware that logs panics that happen inside controllers, like how Rails handles exceptions. It's sufficient to `panic(err)` on unrecoverable errors when you're writing a controller. I'll probably add a note to the readme

2021-05-20 22:30 UTC, CarsonFox commented on controllers/events_handler.go
> +			eventName := string(regexp.MustCompile(`"event_name": ?"([^"]*)"`).FindSubmatch(body)[1])
You can use the struct definitions from [the mocking library](https://github.com/atomicjolt/atomic-event-mocks) to parse the json

2021-05-21 11:13 UTC, sethduffin commented on controllers/events_handler.go
> +func writeAndPanic(w http.ResponseWriter, err error) {
Good to know, I'll remove that

2021-05-21 11:18 UTC, sethduffin commented on controllers/events_handler.go
> +		case "GET":
Oh that's right, I'll remove the `GET` method

2021-05-21 11:30 UTC, sethduffin commented on controllers/events_handler.go
> +			eventName := string(regexp.MustCompile(`"event_name": ?"([^"]*)"`).FindSubmatch(body)[1])
Good idea, I'll go ahead and implement a lib function for that

2021-05-21 12:36 UTC, sethduffin commented on repo/discussion_entry_created_event_repo.go
> +	if err != nil {
Yeah, it might be good to check that, just to be safe. I found a library that takes care of validation if that's something we're interested in. https://github.com/go-playground/validator

2021-05-21 16:02 UTC, CarsonFox approved these changes

2021-05-21 16:19 UTC, kylehovey commented on repo/discussion_entry_created_event_repo.go
> +	err = db.RunInTransaction(ctx, func(tx *pg.Tx) error {
Nice, this is a great call.

2021-05-21 16:20 UTC, kylehovey commented on repo/discussion_entry_created_event_repo.go
> +	db := GetConnection()
The repo has the connection to the database, so I'm pretty sure this connection is redundant.

2021-05-21 16:25 UTC, sethduffin commented on repo/discussion_entry_created_event_repo.go
> +	db := GetConnection()
How do I access that connection through the repo? I thought it'd be `r.DB` but that didn't seem to work

2021-05-24 22:12 UTC, kylehovey approved these changes

2021-05-24 22:12 UTC, kylehovey commented on controllers/events_handler.go
> +					err = c.Repo.DiscussionEntryCreatedEvent.CreateFromPayload(payload)
This is an extremely small nitpick, but since we have other methods with declarative naming conventions along the lines of `VerbFrom(subject)` what are your thoughts on renaming this to `CreateFrom(payload)` instead?

2021-05-24 22:22 UTC, merged