Style updates
atomicjolt/atomic_insight pull request #53
Opened 2021-05-28 22:05 UTC by sethduffin

- Created styles folder with utils (color variables, mixins)
- Replaced color constants with variables
- General style updates

2021-06-01 17:48 UTC, kylehovey requested changes
I think that it is great that we are adding a linter, although I think we should discuss the rules I commented on in the Slack channel. Once that's squared away, I'd love to have linting as CI action so we can ensure that PR's are formatted well before merge.

2021-06-01 17:48 UTC, kylehovey commented on client/.eslintrc.yml
> +  "no-shadow": "off",
This one might be a good one to keep on, I think it makes the code more readable to avoid variable shadowing.

2021-06-01 17:48 UTC, kylehovey commented on client/.eslintrc.yml
> +  "@typescript-eslint/no-explicit-any": "off",
Is there somewhere in the app that requires using an explicit `any` type? If not, I'd argue this should be left on as well.

2021-06-01 17:48 UTC, kylehovey commented on client/.eslintrc.yml
> +  "@typescript-eslint/explicit-module-boundary-types": "off",
We should consider keeping this one on as well, what's your thinking in why it should be disabled?

2021-06-01 18:18 UTC, CarsonFox commented on client/.eslintrc.yml
> +  "@typescript-eslint/no-explicit-any": "off",
Especially with [typescript's really flexible union types](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#union-types), I'd say there's no reason to use `any` in general

2021-06-01 21:41 UTC, kylehovey commented on client/.eslintrc.yml
> +  "no-use-before-define": "off",
What parts of our code trip this rule? We're not sure either way on this one.

2021-06-03 01:47 UTC, kylehovey approved these changes

2021-06-03 19:03 UTC, merged

2021-06-03 19:04 UTC, CarsonFox approved these changes