Implement edit card modal
atomicjolt/atomic_insight pull request #64
Opened 2021-06-11 06:28 UTC by sethduffin

- Added more styled form elements (`Input`, `Label`)
- Implemented searchable `Select` component
- Started developing state management for `Card` component

See commit messages/descriptions

2021-06-11 15:41 UTC, sethduffin commented on client/src/components/atoms/Select/Select.tsx
>    key: OptionKey;
Should this `key` be renamed to `value` to match HTML select options?
This would also describe the field better because we use selects to get the value of an option (eg: a react component in the visual select)

2021-06-11 15:41 UTC, sethduffin commented on client/src/components/atoms/Select/Select.tsx
> +  selectedKey?: OptionKey;
Would `selectedKey` then become `selectedValue` or just `value`?

2021-06-11 15:41 UTC, sethduffin commented on client/src/components/pages/MainPage/MainPage.tsx
>  ];
`layout` will eventually be refactored to only manage card position where the card will actually manage its own width and height (to allow a card to manage its own size property)

2021-06-11 20:10 UTC, kylehovey requested changes

2021-06-11 20:10 UTC, kylehovey commented on client/src/components/molecules/Card/Card.tsx
> +        {data.visual ? React.createElement(data.visual, visualProps) : null}
You shouldn't need to access the `React.createElement` API here. You can assign the value to a variable with a capital first letter and create it with `<Variable {...visualProps} />`. It might also be more readable if you pass in the props one-by one instead of constructing them then passing them in.

2021-06-11 20:10 UTC, kylehovey commented on client/src/components/molecules/Card/Card.tsx
> +  } as React.Attributes;
Should `visualProps` be `IconVisualProps` instead?

2021-06-11 20:10 UTC, kylehovey commented on client/src/components/molecules/Card/Card.tsx
> +        {data.visual ? React.createElement(data.visual, visualProps) : null}
Alternatively, a pattern that doesn't involve passing in a component via props, and some of its props through this components props could help with making things easier to read/maintain.

2021-06-11 20:10 UTC, kylehovey commented on client/src/components/molecules/Card/Card.tsx
> +  const [temp, setTemp] = useState(defaultData);
If we broke up the modal into its own sub-component it might clean up this duplicated state structure. What do you think? e.g. `<CardModal data={} onChange={} />` etc...

2021-06-11 20:29 UTC, sethduffin commented on client/src/components/atoms/Input/Input.tsx
> +  labelDisplay?;
I forgot to remove it.

2021-06-11 20:45 UTC, sethduffin commented on client/src/hooks/use_menu_state.tsx
> +) => void] => {
I agree. I fixed it by defining the types beforehand.

2021-06-11 20:48 UTC, sethduffin commented on client/src/hooks/use_menu_state.tsx
> +  ref?: React.RefObject<HTMLDivElement>
I've renamed it to `menuRef` as it is used to check if the click is still inside the menu. Would there be a better name for it?

2021-06-11 20:53 UTC, sethduffin commented on client/src/components/atoms/Input/Input.tsx
> +  onChange = () => null,
The linter didn't like that so I've removed the initialization and am just checking for it before calling it

2021-06-11 21:03 UTC, sethduffin commented on client/src/components/molecules/Card/Card.tsx
> +  const [temp, setTemp] = useState(defaultData);
Yes, that would be a better approach. Should it exist in the same file or separate?

2021-06-11 21:13 UTC, sethduffin commented on client/src/components/atoms/Select/Select.tsx
> +  gridArea,
Renamed to `gridAreaStyle`

2021-06-11 22:18 UTC, kylehovey commented on client/src/components/molecules/Card/Card.tsx
> +  const [temp, setTemp] = useState(defaultData);
I think a separate file makes more sense

2021-06-11 22:33 UTC, kylehovey commented on client/src/hooks/use_menu_state.tsx
> +) => void] => {
Thanks!

2021-06-11 22:34 UTC, kylehovey commented on client/src/components/atoms/Select/Select.tsx
>    key: OptionKey;
I like that idea. If we are allowing value to be variable in type, this could be generic too. https://www.typescriptlang.org/docs/handbook/2/generics.html

2021-06-11 22:34 UTC, kylehovey commented on client/src/hooks/use_menu_state.tsx
> +  ref?: React.RefObject<HTMLDivElement>
I think that's a good name

2021-06-16 19:39 UTC, kylehovey approved these changes

2021-06-16 19:44 UTC, merged